apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlOVEExTWpZeApPRE0yTWpSYUZ3MDBOVEExTWpZeE9ETTJNalJhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFEQ0g2eGorN01YcnBnV2ZjZGJjbHNXR0JKQTVYU1hZWEVTUGRIc2NVQll1UkU4RjVKQgpBV05Kb3N5NjRIUU93bzlnc3ZUOGxGamhiU0szbFZPQWpEcHdBYjZzOFFBSFVsdmIvU2RuTW80Z1VaOHBMT2lOCmlVUlFTYm1aOHJ4c3F3ZitBdnEyOHplSUhrL2dDTG1XeEtsS2pROUpoSUs5Z29KdGFRa1RUK1lMV1FFSURPcHEKbFIzYWk2ZXN4dkV0Zm5Dc2F5ajVrRTRkWnRadHBMNVdJZEtyWHk1VnFMUlUrOStvL2VLS1BCcVQrb0J2b3ZQSQpKcCtybng2WUM3VllOaTZBVXROd0hXZ2hhNFk2RGhrdUR5TkNnN09RWndLb3JqZTJiYnRQUkZyUlgwdDNlRS9wCmxHSVBtMXViRlE1ZGlMY2J1N05DS2NXNVhMTk1qMGJ4UlVvbkFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlFKQ3BOYjN3Q1g2RFU3OWVRagpWNWl6RHFuZ3R6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFjeFBYRDNWcDByT1YxRDAxazhjYlZ4VXRvU2JzCmNMSmVQTjRFTXlSanc2c1hUSVlFUElQRnFRb0dObFplU3ArVVVzWmFSdjh4Wk5uMXRYQnFsblBsZUZPZ1VsWlMKRWtPMnR3bEJENGdyZVpFQmlNcWFCc1NBUVJJUFJwT3VHYTJjdDltNTUwRWRITk1sdkROVkIvYjZyVVRkN2JXNQozYUdzNm95OTZWbldzQmlsNHZ1azRXcVBoTEZqUE1CbGthTFE3MytZMG1EVWQxbGpyaW85NUIvbU9zRUZWclFqCkJpaGZXbldZOEN1c3VWMFFwSXZBT051REpPdHZsbDRTOFFTcFhHckRHS0F0eHcyUnRlK1hJZkhjRmhTY1cxdTQKaDc1VGVHbXJQUXByMU50Qml3dktZVkpRN0dleUd6VlM5Y2UxeGV1dFRRODVYV0pKUjB2TitqWHd3UT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://483ee799-0f4b-4001-8d13-ac7df446c8e7.k8s.ondigitalocean.com
  name: do-nyc1-my-k8s-cluster
contexts:
- context:
    cluster: do-nyc1-my-k8s-cluster
    user: do-nyc1-my-k8s-cluster-admin
  name: do-nyc1-my-k8s-cluster
current-context: do-nyc1-my-k8s-cluster
users:
- name: do-nyc1-my-k8s-cluster-admin
  user:
    token: dop_v1_4e79c4a334f71679ac2a7d2d565be142599dfc5fbf81ddabd80174272dab54b5
