name: Deploy Infrastructure

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform & Helm
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip curl gnupg lsb-release
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt install terraform -y
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Terraform Init & Apply
        working-directory: terraform
        env:
          TF_VAR_do_token: ${{ secrets.DO_TOKEN }}
          TF_VAR_email: ${{ secrets.EMAIL }}
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Extract Kubeconfig
        run: |
          echo "${{ steps.terraform.outputs.kubeconfig }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Install cert-manager
        run: |
          helm repo add jetstack https://charts.jetstack.io
          helm repo update
          kubectl create namespace cert-manager --dry-run=client -o yaml | kubectl apply -f -
          helm upgrade --install cert-manager jetstack/cert-manager \
            --namespace cert-manager \
            --version v1.14.3 \
            --set installCRDs=true

