name: CertManager Automation

on:
  push:
    paths:
      - 'phase2/**'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.29.0'

      - name: Download and install doctl v1.127.0
        run: |
          DOCTL_VERSION="1.127.0"
          URL="https://github.com/digitalocean/doctl/releases/download/v${DOCTL_VERSION}/doctl-${DOCTL_VERSION}-linux-amd64.tar.gz"
          curl -sL "$URL" -o doctl.tar.gz
          mkdir -p doctl-tmp
          tar -xzf doctl.tar.gz -C doctl-tmp
          sudo mv doctl-tmp/doctl /usr/local/bin/
          rm -rf doctl.tar.gz doctl-tmp
          doctl version

      - name: Authenticate and fetch kubeconfig
        env:
          DIGITALOCEAN_TOKEN: ${{ secrets.DO_TOKEN }}
        run: |
          doctl auth init -t "$DIGITALOCEAN_TOKEN"
          doctl kubernetes cluster kubeconfig save ${{ secrets.CLUSTER_NAME }} --set-current-context
          mkdir -p terraform/phase2
          cp ~/.kube/config terraform/phase2/kubeconfig

      - name: Run Terraform Phase 2 (Cert-Manager ClusterIssuer)
        env:
          TF_VAR_email: ${{ secrets.LETSENCRYPT_EMAIL }}
        run: |
          cd terraform/phase2
          terraform init
          terraform apply -auto-approve

