name: Deploy to DOKS

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.29.0'

      - name: Download and install doctl v1.127.0
        run: |
          DOCTL_VERSION="1.127.0"
          URL="https://github.com/digitalocean/doctl/releases/download/v${DOCTL_VERSION}/doctl-${DOCTL_VERSION}-linux-amd64.tar.gz"
          
          echo "Downloading doctl from $URL"
          
          curl -sL "$URL" -o doctl.tar.gz || { echo "Failed to download doctl"; exit 1; }
          
          mkdir -p doctl-tmp
          tar -xzf doctl.tar.gz -C doctl-tmp || { echo "Failed to extract archive"; exit 1; }
          
          sudo mv doctl-tmp/doctl /usr/local/bin/ || { echo "Failed to move doctl binary"; exit 1; }
          
          rm -rf doctl.tar.gz doctl-tmp
          
          doctl version

      - name: Authenticate doctl
        env:
          DIGITALOCEAN_TOKEN: ${{ secrets.DO_TOKEN }}
        run: |
          doctl auth init -t "$DIGITALOCEAN_TOKEN"

      - name: Run deploy.sh (Terraform Phase 1 + Phase 2)
        env:
          TF_VAR_do_token:        ${{ secrets.DO_TOKEN }}
          TF_VAR_region:          ${{ secrets.DO_REGION }}
          TF_VAR_cluster_name:    ${{ secrets.CLUSTER_NAME }}
          TF_VAR_email:           ${{ secrets.LETSENCRYPT_EMAIL }}
        run: |
          chmod +x scripts/deploy.sh
          ./scripts/deploy.sh

      - name: Install Argo CD CLI
        run: |
          curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv argocd /usr/local/bin/
          argocd version

