name: Deploy to DOKS

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.29.0'

      - name: Install doctl (DigitalOcean CLI)
        run: |
          DOCTL_VERSION="v1.127.0"
          curl -sL "https://github.com/digitalocean/doctl/releases/download/${DOCTL_VERSION}/doctl-${DOCTL_VERSION}-linux-amd64.tar.gz" -o doctl.tar.gz
          mkdir doctl-tmp
          tar -xzf doctl.tar.gz -C doctl-tmp
          sudo mv doctl-tmp/doctl /usr/local/bin/
          doctl version


      - name: Authenticate doctl
        env:
          DIGITALOCEAN_TOKEN: ${{ secrets.DO_TOKEN }}
        run: |
          doctl auth init -t "$DIGITALOCEAN_TOKEN"

      - name: Run deploy.sh (Terraform Phase 1 + Phase 2)
        env:
          TF_VAR_do_token:        ${{ secrets.DO_TOKEN }}
          TF_VAR_region:          ${{ secrets.DO_REGION }}
          TF_VAR_cluster_name:    ${{ secrets.CLUSTER_NAME }}
          TF_VAR_email:           ${{ secrets.LETSENCRYPT_EMAIL }}
        run: |
          chmod +x scripts/deploy.sh
          ./scripts/deploy.sh

      - name: Install Argo CD CLI
        run: |
          curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv argocd /usr/local/bin/
          argocd version

