name: Deploy to DOKS

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.29.0'

      - name: Install doctl
        run: |
          LATEST_VERSION=$(curl -s https://api.github.com/repos/digitalocean/doctl/releases/latest | grep tag_name | cut -d '"' -f 4)
          echo "Latest doctl version: $LATEST_VERSION"
          curl -sL "https://github.com/digitalocean/doctl/releases/download/${LATEST_VERSION}/doctl-${LATEST_VERSION}-linux-amd64.tar.gz" -o doctl.tar.gz
          tar -xzf doctl.tar.gz
          sudo mv doctl /usr/local/bin/
          doctl version

      - name: Doctl Auth
        env:
          DIGITALOCEAN_TOKEN: ${{ secrets.DO_TOKEN }}
        run: |
          doctl auth init -t "$DIGITALOCEAN_TOKEN"

      - name: Run deploy.sh
        env:
          TF_VAR_do_token:        ${{ secrets.DO_TOKEN }}
          TF_VAR_region:          ${{ secrets.DO_REGION }}
          TF_VAR_cluster_name:    ${{ secrets.CLUSTER_NAME }}
          TF_VAR_email:           ${{ secrets.LETSENCRYPT_EMAIL }}
        run: |
          chmod +x scripts/deploy.sh
          ./scripts/deploy.sh

      - name: Install Argo CD CLI
        run: |
          curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv argocd /usr/local/bin/

